### ISSUE TITLE
JavaScript error due to <meta> tag in template

### ISSUE THREAD

**Issue by chriscdn** [vuepressjs/vuepress-theme-blog#78]
- [x] I confirm that this is an issue rather than a question.

## Bug report

In [this commit](https://github.com/vuepressjs/vuepress-theme-blog/commit/2bdb39b27cec2ffd89e2bf7469fd322cce90fd73#diff-910e3b04dac2d84827612c65e451e88e) a `<meta>` tag is added to the page.  This causes VuePress to throw an error since the `updateMetaTags()` function in `updateMeta.js` assumes (correctly) that all `<meta>` tags are below `<head>`.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 
- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

- Download this repository as a ZIP file
- upgrade all the dependencies (e.g., `yarn upgrade --latest`)
- build (`yarn example:build`)
- serve the output in `example/.vuepress/dist/`
- inspect the page and notice the JavaScript error

#### What is expected?

No JavaScript error.

#### What is actually happening?
> {"stack":"Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.\n at /assets/js/app.bff2e1e0.js:8:102722\n at Array.forEach (<anonymous>)\n at Xt (/assets/js/app.bff2e1e0.js:8:102687)\n at i.updateMeta (/assets/js/app.bff2e1e0.js:8:102369)\n at i.mounted (/assets/js/app.bff2e1e0.js:8:102204)\n at Bt (/assets/js/app.bff2e1e0.js:6:11294)\n at Qe (/assets/js/app.bff2e1e0.js:6:25252)\n at Object.insert (/assets/js/app.bff2e1e0.js:6:20274)\n at O (/assets/js/app.bff2e1e0.js:6:56250)\n at _n.__patch__ (/assets/js/app.bff2e1e0.js:6:57204)"}
 /assets/js/app.bff2e1e0.js:6
#### Other relevant information

**Comment by newsbielt703** [comment]
Thanks for the report.

**Comment by newsbielt703** [comment]
> When a `<meta>` tag contains `itemprop` attr, it's allowed to be placed inside html body.

I suppose this issue could be resolved by updating `updateMeta.js` file or leveraging `itemref ` attr. @Kocal  Would you like to resolve it?

**Comment by Kocal** [comment]
Yes I can take a look, I will try to work on it tonight.

**Comment by Kocal** [comment]
PR opened at https://github.com/vuejs/vuepress/pull/2403

I prefered to check over `<meta>` parent element instead of checking if `itemref` attribute exists, because it seems that `<meta itemprop="...">` are also accepted in `<head>` (https://stackoverflow.com/a/22415563)

What do you think?
